package ram_pack.ram_check_and_convert;

public enum CodeSubstringType
{
	LABEL_DEFINITION,
	LABEL_CALL,
	LABEL_TWO_POINTS,
	COMMAND,
	MACRO_CALL,
	COMMENT,
	ARGUMENT,
	TRASH,
	SYMBOL,
	EQUAL,
	STAR,
	NUMBER,
	MACRO_DEFINITION_START,
	MACRO_NAME_DEFINITION,
	MACRO_ARGUMENT_DEFINITION,
	MACRO_ARGUMENT,
	MACRO_DEFINITION_END,
	SPACES_AND_TABULATIONS,
	INVALID_MACRO_START,
	INVALID_MACRO_END,
	INVALID_MACRO_NAME,
	INVALID_ARGUMENT,
	INVALID_LABEL_DEFINITION,
	INVALID_COMMAND
}
